Repository ilkeraslan/repeatcard, pull requests merged in 2020-10, with the labels that each got.

#86 update to adapter position
  app/src/main/java/it/ilker/repeatcard/ui/directories/DirectoriesAdapter.kt
  app/src/main/java/it/ilker/repeatcard/ui/directory/DirectoryAdapter.kt
  app/src/main/java/it/ilker/repeatcard/ui/home/HomeAdapter.kt
  app/src/main/java/it/ilker/repeatcard/ui/logs/LogsAdapter.kt
  app/src/main/java/it/ilker/repeatcard/ui/results/ResultsAdapter.kt
Labels: bug, hacktoberfest

#85 Added environment variables
  app/build.gradle
Labels: enhancement, hacktoberfest

#88 Enabled proguard
  app/build.gradle
  app/proguard-rules.pro
  buildSrc/src/main/java/Dependencies.kt
Labels: bug, good first issue, hacktoberfest, hacktoberfest-accepted

#89 Change primary dark color
  app/src/main/res/values/styles.xml
Labels: bug, hacktoberfest

#91 Fix kotlin dsl warnings
  buildSrc/build.gradle.kts
Labels: bug, hacktoberfest, hacktoberfest-accepted

#92 Disable proguard on debug
  app/build.gradle
Labels: hacktoberfest

#105 Migrating all LiveData to Coroutines StateFlow
  README.md
  app/src/main/java/it/ilker/repeatcard/ui/directories/DirectoriesFragment.kt
  app/src/main/java/it/ilker/repeatcard/ui/directories/DirectoriesViewModel.kt
  app/src/main/java/it/ilker/repeatcard/ui/directory/DirectoryScreen.kt
  app/src/main/java/it/ilker/repeatcard/ui/directory/DirectoryViewModel.kt
  app/src/main/java/it/ilker/repeatcard/ui/flashcarddetail/FlashcardDetailScreen.kt
  app/src/main/java/it/ilker/repeatcard/ui/flashcarddetail/FlashcardDetailViewModel.kt
  app/src/main/java/it/ilker/repeatcard/ui/flashcardedit/EditFlashcardScreen.kt
  app/src/main/java/it/ilker/repeatcard/ui/flashcardedit/EditFlashcardViewModel.kt
  app/src/main/java/it/ilker/repeatcard/ui/home/HomeScreen.kt
  app/src/main/java/it/ilker/repeatcard/ui/home/HomeViewModel.kt
  app/src/main/java/it/ilker/repeatcard/ui/question/QuestionDetailScreen.kt
  app/src/main/java/it/ilker/repeatcard/ui/question/QuestionViewModel.kt
  app/src/main/java/it/ilker/repeatcard/ui/quiz/QuizFragment.kt
  app/src/main/java/it/ilker/repeatcard/ui/quiz/QuizScreen.kt
  app/src/main/java/it/ilker/repeatcard/ui/quiz/QuizViewModel.kt
  app/src/main/java/it/ilker/repeatcard/ui/results/ResultsScreen.kt
  app/src/main/java/it/ilker/repeatcard/ui/results/ResultsViewModel.kt
  app/src/main/java/it/ilker/repeatcard/ui/review/FlashcardReviewScreen.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: enhancement, hacktoberfest

#108 Fix/detekt
  README.md
  app/src/main/java/it/ilker/repeatcard/ui/flashcardadd/AddFlashcardScreen.kt
  app/src/main/java/it/ilker/repeatcard/ui/quiz/QuizViewModel.kt
Labels: enhancement

#107 Added Progress Loader for all screens
  app/src/main/java/it/ilker/repeatcard/ui/directories/DirectoriesFragment.kt
  app/src/main/java/it/ilker/repeatcard/ui/directory/DirectoryScreen.kt
  app/src/main/java/it/ilker/repeatcard/ui/flashcarddetail/FlashcardDetailScreen.kt
  app/src/main/java/it/ilker/repeatcard/ui/flashcardedit/EditFlashcardScreen.kt
  app/src/main/java/it/ilker/repeatcard/ui/home/HomeScreen.kt
  app/src/main/java/it/ilker/repeatcard/ui/question/QuestionDetailScreen.kt
  app/src/main/java/it/ilker/repeatcard/ui/quiz/QuizFragment.kt
  app/src/main/java/it/ilker/repeatcard/ui/quiz/QuizScreen.kt
  app/src/main/java/it/ilker/repeatcard/ui/results/ResultsScreen.kt
  app/src/main/java/it/ilker/repeatcard/ui/review/FlashcardReviewScreen.kt
  app/src/main/res/layout/activity_add_flashcard.xml
  app/src/main/res/layout/activity_quiz.xml
  app/src/main/res/layout/activity_quiz_base.xml
  app/src/main/res/layout/directories_fragment.xml
  app/src/main/res/layout/directory_layout.xml
  app/src/main/res/layout/flashcard_detail_layout.xml
  app/src/main/res/layout/flashcard_review_layout.xml
  app/src/main/res/layout/home_fragment.xml
  app/src/main/res/layout/quiz_fragment.xml
  app/src/main/res/layout/screen_results.xml
  app/src/main/res/values/styles.xml
Labels: enhancement, hacktoberfest

#109 Update README.md
  README.md
Labels: enhancement
